"""Add class groups and schedule info

Revision ID: 00fb36ea3bf3
Revises: 9824630c8980
Create Date: 2026-03-01 22:47:14.064237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fb36ea3bf3'
down_revision: Union[str, Sequence[str], None] = '9824630c8980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_group_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courses', sa.Column('class_group_id', sa.UUID(), nullable=True))
    op.add_column('courses', sa.Column('schedule_info', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'courses', 'class_groups', ['class_group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'schedule_info')
    op.drop_column('courses', 'class_group_id')
    op.drop_table('class_enrollments')
    op.drop_table('class_groups')
    # ### end Alembic commands ###
