"""Add student_id to ParentProfile

Revision ID: 9824630c8980
Revises: 64e880123b83
Create Date: 2026-03-01 21:18:51.814886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9824630c8980'
down_revision: Union[str, Sequence[str], None] = '64e880123b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_profiles', sa.Column('student_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'parent_profiles', 'users', ['student_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent_profiles', type_='foreignkey')
    op.drop_column('parent_profiles', 'student_id')
    # ### end Alembic commands ###
